import 'package:flutter/material.dart';

class FAQsScreen extends StatelessWidget {
  const FAQsScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('FAQs'),
        backgroundColor: const Color(0xFFF9F5D7),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: ListView(
          children: const [
            FAQItem(
              question: 'What is a cryptocurrency wallet?',
              answer: 'A cryptocurrency wallet is a digital wallet that allows you to store, send, and receive cryptocurrencies like MGC securely.',
            ),
            FAQItem(
              question: 'How do I create a wallet?',
              answer: 'You can create a wallet by following the setup instructions in the app. Ensure you save your seed phrase securely.',
            ),
            FAQItem(
              question: 'What is a seed phrase?',
              answer: 'A seed phrase is a series of words generated by your wallet that can be used to recover your wallet if you lose access.',
            ),
            FAQItem(
              question: 'How can I send MGC to another wallet?',
              answer: 'To send MGC, navigate to the Send screen, enter the recipient’s address and the amount, and confirm the transaction.',
            ),
            FAQItem(
              question: 'How do I check my transaction history?',
              answer: 'You can view your transaction history by going to the Home screen and selecting the transaction history option.',
            ),
            FAQItem(
              question: 'What should I do if my transaction is stuck?',
              answer: 'If a transaction is stuck, ensure you have sufficient funds for gas fees. You may need to wait for network confirmations.',
            ),
            FAQItem(
              question: 'How can I secure my wallet?',
              answer: 'Ensure you use a strong password, enable two-factor authentication, and keep your seed phrase private and secure.',
            ),
            FAQItem(
              question: 'What to do if I forgot my password?',
              answer: 'If you forget your password, you can reset it using the recovery options provided in the app.',
            ),
          ],
        ),
      ),
    );
  }
}

class FAQItem extends StatefulWidget {
  final String question;
  final String answer;

  const FAQItem({Key? key, required this.question, required this.answer}) : super(key: key);

  @override
  _FAQItemState createState() => _FAQItemState();
}

class _FAQItemState extends State<FAQItem> {
  bool _isExpanded = false;

  @override
  Widget build(BuildContext context) {
    return Card(
      margin: const EdgeInsets.symmetric(vertical: 8.0),
      child: Column(
        children: [
          ListTile(
            title: Text(
              widget.question,
              style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
            trailing: Icon(
              _isExpanded ? Icons.expand_less : Icons.expand_more,
              color: Colors.black,
            ),
            onTap: () {
              setState(() {
                _isExpanded = !_isExpanded;
              });
            },
          ),
          if (_isExpanded)
            Padding(
              padding: const EdgeInsets.all(16.0),
              child: Text(
                widget.answer,
                style: const TextStyle(fontSize: 14, color: Colors.black54),
              ),
            ),
        ],
      ),
    );
  }
}
